name: devops engineer sandra odogwu pipeline

on: [push]
jobs:

  job1:
    name: cat peace.yaml
    runs-on: ubuntu-24.04
    steps:
    run: cat peace.yaml


  job2:
    name: sandra to cook jollof rice


