name: devops engineer sandra odogwu pipeline

on: [push]
jobs:

  job1:
    name: cat peace.yaml
    runs-on: ubuntu-24.04
    steps:
      - name: Print the content of peace.yaml
        run: cat peace.yaml

      # - name: Print the content
      #   run: cat peace.yaml


  job2:
    name: sandra to cook jollof rice


